---
# tasks file for gatling

- name: Install system dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - "unzip"  # For unarchive module
    - "debconf"  # For java installation
    - "debconf-utils"  # java install
    - "rsync"  # For synchronize module

- name: Download zipped Gatling bundle
  get_url:
    url: "{{gatling_download.url}}"
    dest: "~/gatling-charts-highcharts-bundle-2.2.5-bundle.zip"
    mode: "a+rxw"
    checksum: "md5:{{gatling_download.md5}}"
    validate_certs: no

- name: Install java for Gatling.io
  include: java-install.yml

- name: Check if the gatling distribution was unarchived
  stat:
    path: "~/gatling-charts-highcharts-bundle-2.2.5"
  register: gatling_unarchived

- name: Unzip the Gatling bundle
  unarchive:
    src: "~/gatling-charts-highcharts-bundle-2.2.5-bundle.zip"
    dest: "~/"
    remote_src: yes
    creates: no
  when: gatling_unarchived.stat.exists == False or gatling_unarchived.stat.isdir == False

- name: Create a folder to receive the merged reports
  file:
    path: "{{gatling_simulation.reports_directory}}"
    state: directory
    mode: "a+rw"

- name: Copy the simulation folders to the Gatling machines
  template:
    src: "./templates/{{item}}.scala"
    dest: "{{gatling_simulation.directory}}"
  with_items:
    - "AbstractTranquility"
    - "DataGenerator"
    - "DruidSineSignalSimulation"
    - "MeasureFeeder"
    - "StaresRamp"
    - "TranquilityInstance"